name: mernstack

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout/@v4

            - name: welcome
              run : echo "hello man i love you keep pushing "
            - name: list
              run : ls
            - name: Read file
              run : cat README.md
            - name: ascii artwork
              run: cosway -f dragon "ohreb a taaaaher" >> taher.txt