name: generate 

on:
    push

jobs:
    ascii:
        runs-on: ubuntu-latest
        steps:
            - name: chekckout
              uses: actions/checkout/@v4
            - name: install cowsay
              run: sudo apt-get install cowsay -y 
            - name: execute cowsay
              run: cowsay -f taher "ohreb a tahe" >> taher.txt
            - name: test
              run: grep -i "taher" taher.txt
            - name: read
              run: cat taher.txt



